server:
  port: 8083

spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"