server:
  port: 8082

spring:
  application:
    name: client
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/client
    password: 'postgres'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka